config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => 'jobs', constraints: AdminConstraint.new

  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  namespace :admin, constraints: AdminConstraint.new do
    resources :users
  end

  resources :posts

  root 'pages#index'
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/shared/_files.html.erb
<% if files.any? %>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="list-inline">
          <% files.each do |file| %>
            <li class="list-inline-item border p-2">
              <%= link_to rails_blob_path(file, disposition: "attachment") do %>
                <i class="bi bi-file-earmark-check-fill"></i>
                <span class="text-dark">
                  <%= p file.blob.filename.to_s.truncate(20, omission: "...#{file.blob.filename.extension}") %>
                </span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="row text-center text-muted ">
      <p>No files</p>
    </div>
  <% end %>

app/views/shared/_images.html.erb
<% if images.any? %>
  <div class="container">
    <div class="flex-container justify-content-center flex-md-wrap">
      <% images.each do |image| %>
        <%= link_to image_tag(image.variable? ? image.variant(resize_to_limit: [250, nil]) : image), 
                url_for(image), class: "img-thumbnail rounded", target: '_blank' %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row text-center text-muted ">
    <p>No images</p>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-primary text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <% if user_signed_in? %>
            <li><%= nav_tab 'Home', root_path,
            class: 'nav-link px-2', current_page: current_page %></li>
            <li><%= nav_tab 'Posts', posts_path,
            class: 'nav-link px-2', current_page: current_page %></li>
            <% if policy([:admin, :user]).index? %>
              <li><%= nav_tab 'Users', admin_users_path,
              class: 'nav-link px-2', current_page: current_page %></li>
            <% end %>
          <% end %>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#',
                class: 'nav-link px-2 dropdown-toggle text-white',
                data: {"bs-toggle": 'dropdown'} do %>
                <%= current_user.first_name %>
              <% end %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Edit profile', edit_user_path(current_user),
                    class: 'dropdown-item' %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to 'Sign out', session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Sign up', new_user_path,
              class: 'nav-link px-2', current_page: current_page %></li>
            <li><%= nav_tab 'Sign in', new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>